In [1]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("Hello-SimpleAI/chatgpt-detector-roberta-chinese")
model = AutoModelForSequenceClassification.from_pretrained("Hello-SimpleAI/chatgpt-detector-roberta-chinese")

In [2]:
import torch

text = '''
多項民調顯示，民眾黨總統參選人柯文哲領先國、民兩黨總統參選人；
台灣民意基金會董事長游盈隆認為，年輕選民不是今天才疏離民進黨；
把年輕選民逐漸疏離民進黨的現象，歸因於賴清德個人風格，甚至穿著，
基本上是犯了嚴重「見樹不見林」的謬誤。
'''

inputs = tokenizer(text, return_tensors="pt")

with torch.no_grad():
    logits = model(**inputs).logits
    
print(model.config.id2label)
print(logits)

predicted_class_id = logits.argmax().item()
model.config.id2label[predicted_class_id]

{0: 'Human', 1: 'ChatGPT'}
tensor([[ 4.8209, -4.9549]])


'Human'

In [9]:
import torch

text = '''
這只是陳氏太極拳招式的一些例子，實際上陳氏太極拳擁有更多的招式和套路。
每個招式都有特定的動作和意義，結合了太極拳的原則，如以柔克剛、以圓融化等。
通過不斷練習和體驗，可以更好地理解和運用陳氏太極拳的招式。
如果你對陳氏太極拳有更深入的興趣，建議尋找一位經驗豐富的太極拳教練或學習資源，
以深入學習和探索。
'''

inputs = tokenizer(text, return_tensors="pt")

with torch.no_grad():
    logits = model(**inputs).logits
    
print(model.config.id2label)
print(logits)

predicted_class_id = logits.argmax().item()
model.config.id2label[predicted_class_id]

{0: 'Human', 1: 'ChatGPT'}
tensor([[-4.9169,  4.9372]])


'ChatGPT'

In [10]:
import torch

text = '''
由於網際網路的快速發展，在網路上消費變得越來越方便，也越來越常見。
現今消費者在網路消費前，會從社群網站的公開討論上比較商品間的差異，
這已變成必做的功課。
'''

inputs = tokenizer(text, return_tensors="pt")

with torch.no_grad():
    logits = model(**inputs).logits
    
print(model.config.id2label)
print(logits)

predicted_class_id = logits.argmax().item()
model.config.id2label[predicted_class_id]

{0: 'Human', 1: 'ChatGPT'}
tensor([[ 4.3189, -4.6882]])


'Human'